### get root path
GET  http://localhost:3000/ HTTP/1.1


### get ttech route
GET  http://localhost:3000/ttech HTTP/1.1


### get all colors
GET  http://localhost:3000/colors HTTP/1.1


### get one color
GET http://localhost:3000/colors/ HTTP/1.1


### create a color
POST http://localhost:3000/colors HTTP/1.1
Content-Type: application/json

{
  "hexCode": "#ababab",
  "name": "Color1"
}


### update color
PATCH   http://localhost:3000/colors/ HTTP/1.1
Content-Type: application/json

{
  "hexCode": "#123456"
  "name": "Color2"
}


### delete color
DELETE http://localhost:3000/colors/6a970385d94c45989eaac146 HTTP/1.1


### get all students
GET  http://localhost:3000/students HTTP/1.1


### get one student
GET http://localhost:3000/students/6a9624ce47475af207c98603 HTTP/1.1


### create a student
POST http://localhost:3000/students HTTP/1.1
Content-Type: application/json

{
  "firstName": "Carlos",
  "lastName": "Hernandez",
  "email": "Carlos@gmail.com",
  "age": "24",
  "currentCollege": "Cooleg"
}


### update student
PATCH   http://localhost:3000/students/6a9624ce47475af207c98603 HTTP/1.1
Content-Type: application/json

{
  "lastName": "Deer"
}


### delete student
DELETE http://localhost:3000/students/6a970385d94c45989eaac146 HTTP/1.1


### post register
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "fullName": "test",
  "email": "test@gmail.com",
  "password": "test",
  "userType": "reg"
}


### post login
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "fullName": "test",
  "email": "test@gmail.com",
  "password": "test",
  "userType": "reg"
}


### post logout
POST http://localhost:3000/auth/logout HTTP/1.1


### protected route
GET http://localhost:3000/auth/protected HTTP/1.1
Authorization: Bearer